- import_tasks: generic-feature-template.yml
  run_once: True
  vars:
    template_list: "{{ Feature_Templates['Banner_Templates'] }}"
    template: sdwan-templates/feature-banner.j2
    folder: feature-banner
  when: Feature_Templates['Banner_Templates'] is defined
