- name: Clean rendered templates
  file:
    path: "{{item}}"
    state: absent
    force: true
  run_once: True
  with_fileglob:
    - "{{role_path}}/files/rendered_templates/{{ folder }}/*"

- name: Render template
  template: src={{ template }} dest={{role_path}}/files/rendered_templates/{{ folder }}/{{ item.templateName }}.json
  when: item.state  != "ignore" and item.state  != "absent"
  with_items: "{{ loop_over }}"

# reference here: https://stackoverflow.com/questions/29399581/using-set-facts-and-with-items-together-in-ansible

- name: Loading templates from filesystem
  set_fact:
    generic_template: "{{lookup('file', '{{item}}') }}"
  with_fileglob:
     - "{{role_path}}/files/rendered_templates/{{ folder }}/*.json"
  register: generic_template_registered_list

- name: Creating a list of templates
  set_fact:
    present_feature_list: "{{ generic_template_registered_list.results | map(attribute = 'ansible_facts.generic_template') | list }}"

- name: Creating an empty list of templates to be removed
  set_fact:
    absent_template_list: []
  no_log: True

- name: Creating a list of templates to be removed
  set_fact:
    absent_template_list: "{{ absent_template_list|default([]) + [ {'templateName': item.templateName } ] }}"
  when: item.state  == "absent"
  with_items: "{{ loop_over }}"

#- vmanage_feature_template:
#    user: "admin"
#    host: "localhost:8443"
#    password: "admin"
#    state: present
#    name: "{{ item.templateName }}"
#    description: "{{ item.templateDescription }}"
#    definition: "{{ item.templateDefinition }}"
#    template_type: "{{ item.templateType }}"
#    device_type: "{{ item.deviceType }}"
#    template_min_version:  "{{ item.templateMinVersion }}"
#    factory_default: "{{ item.factoryDefault }}"
#  loop: "{{feature_banner_list}}"

- name: Interact with the vManage to create templates
  vmanage_feature_template:
    user: "{{ansible_user}}"
    host: "{{ansible_host}}:{{ansible_port}}"
    password: "{{ansible_password}}"
    state: present
    aggregate: "{{present_feature_list}}"
  when: present_feature_list

- name: Interact with the vManage to delete templates
  vmanage_feature_template:
    user: "{{ansible_user}}"
    host: "{{ansible_host}}:{{ansible_port}}"
    password: "{{ansible_password}}"
    state: absent
    aggregate: "{{absent_template_list}}"
  when: absent_template_list