- include_tasks: get-cookie.yml
  when: viptela_api_cookie is not defined

- name: Push Certificates
  uri:
    url: "https://{{ vmanage_ip }}/dataservice/certificate/vedge/list?action=push"
    method: POST
    headers:
      Cookie: "{{ viptela_api_cookie }}"
    validate_certs: "{{ validate_certs }}"
    return_content: yes
  register: uri_results
  delegate_to: localhost
  retries: 60
  delay: 10
  until: uri_results is not failed