- name: Get list of current software (only for debug)
  tags: check
  vmanage_software_facts:
    user: "{{ansible_user}}"
    host: "{{ansible_host}}:{{ansible_port}}"
    password: "{{ansible_password}}"
  register: software_facts

- name: Debug
  tags: check
  debug:
    var: software_facts


#- name: Upload the file image if does not exists
#  vmanage_software_upload:
#    user: "{{ansible_user}}"
#    host: "{{ansible_host}}:{{ansible_port}}"
#    password: "{{ansible_password}}"
#    state: present
#    file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"


#- name: Upload the file image if does not exists
#  vmanage_software_upload:
#    user: "{{ansible_user}}"
#    host: "{{ansible_host}}:{{ansible_port}}"
#    password: "{{ansible_password}}"
#    state: present
#    file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"
#  ignore_errors: yes

- name: Upload the file image if does not exists (Aggregate)
  vmanage_software_upload:
    user: "{{ansible_user}}"
    host: "{{ansible_host}}:{{ansible_port}}"
    password: "{{ansible_password}}"
    state: present
    aggregate:
      - file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"
      - file: "{{role_path}}/files/software/viptela-18.3.6-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-18.3.5-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-19.1.0-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-18.4.1-x86_64.tar.gz"
#- name: Upload the file image if does not exists (Aggregate)
#  vmanage_software_upload:
#    user: "{{ansible_user}}"
#    host: "{{ansible_host}}:{{ansible_port}}"
#    password: "{{ansible_password}}"
#    state: present
#    aggregate:
#      - file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-18.2222223.7-x86_64.tar.gz"
#      - file: "{{role_path}}/files/software/viptela-18.3.7-x86_64.tar.gz"
#  ignore_errors: yes


#- name: Software upgrade
#  vmanage_device_install:
#    user: "{{ansible_user}}"
#    host: "{{ansible_host}}:{{ansible_port}}"
#    password: "{{ansible_password}}"
#    software:
#    aggregate:


#- name: Software install
#  vmanage_software_upgrade:
#    user: "{{ansible_user}}"
#    host: "{{ansible_host}}:{{ansible_port}}"
#    password: "{{ansible_password}}"
#    devices:
#      - deviceIP: "1.1.1.2"
#        deviceId: "5b3c6307-cfff-431c-ae5a-d30814055071"
#    deviceType: controller
#    activate: false
#    set_default: false
#    version: 18.3.6



- name: Software install
  vmanage_software_upgrade:
    user: "{{ansible_user}}"
    host: "{{ansible_host}}:{{ansible_port}}"
    password: "{{ansible_password}}"
    devices:
      - deviceIP: "4.4.4.65"
        deviceId: "46c18a49-f6f3-4588-a49a-0b1cc387f179"
      - deviceIP: "4.4.4.60"
        deviceId: "100faff9-8b36-4312-bf97-743b26bd0211"
      - deviceIP: "4.4.4.61"
        deviceId: "f3d4159b-4172-462c-9c8d-8db76c31521d"
      - deviceIP: "4.4.4.64"
        deviceId: "0435c3e8-d3a0-4c6b-af0a-f95d41974d69"
    deviceType: vedge
    activate: true
    set_default: true
    version: 18.3.6